name: paulonia_cache_image
description: Flutter package for cache images in storage or memory from the network or Google Cloud Storage. It supports Android, iOS and Web.
version: 1.1.0
homepage: https://paulonia.dev
repository: https://github.com/PauloniaAQP/paulonia_cache_image

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^10.2.7
  firebase: ^9.0.2
  path_provider: ^2.0.9
  hive: ^2.0.5
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
